SELECT 
  business_id,
  name,
  address,
  city,
  state,
  postal_code,
  ST_GeogPoint(longitude, latitude) ASlocation, 
  stars,
  review_count,
  is_open,
  SPLIT(categories, ', ') AS categories,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Monday"'), '-')[OFFSET(0)], '"') AS open_monday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Monday"'), '-')[OFFSET(1)], '"') AS close_monday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Tuesday"'), '-')[OFFSET(0)], '"') AS open_tuesday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Tuesday"'), '-')[OFFSET(1)], '"') AS close_tuesday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Wednesday"'), '-')[OFFSET(0)], '"') AS open_wednesday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Wednesday"'), '-')[OFFSET(1)], '"') AS close_wednesday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Thursday"'), '-')[OFFSET(0)], '"') AS open_thursday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Thursday"'), '-')[OFFSET(1)], '"') AS close_thursday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Friday"'), '-')[OFFSET(0)], '"') AS open_friday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Friday"'), '-')[OFFSET(1)], '"') AS close_friday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Saturday"'), '-')[OFFSET(0)], '"') AS open_saturday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Saturday"'), '-')[OFFSET(1)], '"') AS close_saturday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Sunday"'), '-')[OFFSET(0)], '"') AS open_sunday,
  TRIM(SPLIT(JSON_QUERY(hours, '$."Sunday"'), '-')[OFFSET(1)], '"') AS close_sunday,
FROM `dana-quality-test.dana_quality_test.yelp_academic_dataset_business`
